
name: swintronics
networks:
  default:
    name: tailnet
include:
  - "tailscale/compose.yml"
  - "traefik/compose.yml"
  - "immich-app/compose.yml"
  - "dozzle/compose.yml"
  - "paperless/compose.yml"
  - "uptime-kuma/compose.yml"
  - "stirling-pdf/compose.yml"
  
  